import = [
    "~/AppData/Roaming/alacritty/themes/themes/gruber_darker.toml"
]

[keyboard]
bindings = [{ key = "Space", mods = "Control", chars = "\u0000" }]

[shell]
program = "wsl"
args = [
    "-d",
    "Ubuntu",
    "--cd",
    "~"
]

# Включить антиалиасинг
[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font", style = "Bold Italic" }
size = 11.0

# Настройки окна
[window]
padding = { x = 5, y = 5 }
